export const ShipTypes: Record<number, string> = {
  1: 'Aggregates Carrier',
  2: 'Anchor Handling Vessel',
  3: 'Asphalt/Bitumen Tanker',
  4: 'Bulk Carrier',
  5: 'Bunkering Tanker',
  6: 'Cable Layer',
  7: 'Cargo',
  8: 'Cement Carrier',
  9: 'Chemical Tanker',
  10: 'Container Ship',
  11: 'Crew Boat',
  12: 'Crude Oil Tanker',
  13: 'Dredger',
  14: 'Drill Ship',
  15: 'Fire Fighting Vessel',
  16: 'Fish Carrier',
  17: 'Fishing',
  18: 'Fishing Vessel',
  19: 'Floating Crane',
  20: 'Floating Storage/Production',
  21: 'General Cargo',
  22: 'Heavy Load Carrier',
  23: 'High Speed Craft',
  24: 'Icebreaker',
  25: 'Inland Passengers Ship',
  26: 'Landing Craft',
  27: 'Livestock Carrier',
  28: 'LNG Tanker',
  29: 'LPG Tanker',
  30: 'Military Ops',
  31: 'Navigation Aids',
  32: 'Obo Carrier',
  33: 'Offshore Structure',
  34: 'Offshore Vessel',
  35: 'Oil Products Tanker',
  36: 'Oil/Chemical Tanker',
  37: 'Ore Carrier',
  38: 'Special Craft',
  39: 'Special Cargo',
  40: 'Special Fishing Vessel',
  41: 'Special Passenger Vessel',
  42: 'Special Pleasure Craft',
  43: 'Special Tanker',
  44: 'Passenger',
  45: 'Passenger/Cargo Ship',
  46: 'Passenger Vessel',
  47: 'Patrol Vessel',
  48: 'Pilot Boat',
  49: 'Platform',
  50: 'Pollution Control Vessel',
  51: 'Pusher Tug',
  52: 'Reefer',
  53: 'Research/Survey Vessel',
  54: 'Ro-Ro/Passenger Vessel',
  55: 'Ro-Ro/Vehicles Carrier',
  56: 'Sailing Vessel',
  57: 'Search & Rescue',
  58: 'Service Vessel',
  59: 'Special Tug',
  60: 'Supply Vessel',
  61: 'Tanker',
  62: 'Training Ship',
  63: 'Trawler',
  64: 'Tug',
  65: 'Tug/Supply Vessel',
  66: 'Water Tanker',
  67: 'Yacht',
  68: 'Barge',
  69: 'Inland Tanker',
  70: 'Inland Cargo',
  71: 'Inland Tug',
  900: 'Unspecified',
  901: 'Navigation Aids',
  902: 'Other Fishing',
  903: 'Other Special Craft',
  904: 'High Speed Craft',
  906: 'Other Passenger',
  907: 'Other Cargo',
  908: 'Other Tanker',
  909: 'Other Pleasure Craft',
};
